    server {
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;
    client_max_body_size 1048576;

    location /cgi-bin {
        methods GET POST;
        root ./www/cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .py /usr/local/bin/python3;
    }
}