server {
    listen 127.0.0.1:19091;
    server_name first;

    root ./www;
    index index.html;
    client_max_body_size 1048576;
    client_timeout 30;

    location / {
        methods GET;
        root ./www;
        index index.html;
        autoindex off;
        upload_enable off;
    }
}

server {
    listen 127.0.0.1:19091;
    server_name second;

    root ./www;
    index index.html;
    client_max_body_size 1048576;
    client_timeout 30;

    location / {
        methods GET;
        root ./www;
        index index.html;
        autoindex off;
        upload_enable off;
    }
}
