server {
    listen 127.0.0.1:8080;
    server_name empty_error_page_test;

    root ./www;
    index index.html;
    client_max_body_size 1048576;

    error_page 404 ;

    location / {
        methods GET;
    }
}
