server {
    listen 127.0.0.1:8080;
    server_name cgi_relative_test;

    root ./www;
    index index.html;
    client_max_body_size 1048576;

    location /cgi-bin {
        methods GET POST;
        root ./www/cgi-bin;
        cgi .py python3;
    }
}
