server {
    listen 127.0.0.1:8080;
    server_name validator_test;

    root ./www;
    index index.html;
    client_max_body_size 1048576;

    location /uploads {
        methods GET POST DELETE;
        root ./www/uploads;
        upload_enable on;
    }
}
