server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10M;
    error_page 404 /errors/404.html;

    location / {
        root ./www;
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

    location /upload {
        root ./www;
        allowed_methods POST;
        upload_dir ./uploads;
        client_max_body_size 100M;
    }

    location /cgi-bin {
        root ./cgi-bin;
        cgi_extension .py;
        allowed_methods GET POST;
    }

    location /files {
        root ./uploads;
        allowed_methods GET DELETE;
        autoindex on;
    }
}
