print("Status: 201 Created")
print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("<head>")
print("<meta charset=\"utf-8\">")
print("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
print("<title>CGI Status demo · webserv</title>")
print("<link rel=\"stylesheet\" href=\"/css/style.css\">")
print("</head>")
print("<body>")
print("<header class=\"nav\"><div class=\"nav-inner\">")
print("<a href=\"/index.html\" class=\"brand\"><span class=\"brand-dot\"></span><span><span class=\"brand-prompt\">~/</span>webserv</span></a>")
print("<nav class=\"nav-links\"><a href=\"/cgi.html\">Back to CGI</a><a href=\"/index.html\">Home</a></nav>")
print("</div></header>")
print("<main class=\"fade-in\"><section class=\"container\">")
print("<span class=\"eyebrow\">// Status: 201 Created</span>")
print("<h1>CGI custom Status header</h1>")
print("<p class=\"lead\" style=\"color:var(--muted)\">This CGI script returned <code>Status: 201 Created</code>. The server should use it as the HTTP status.</p>")
print("</section></main>")
print("<footer><div class=\"container\"><span>webserv</span><span class=\"sep\">/</span><span>CGI status demo</span></div></footer>")
print("</body></html>")
