import html
import os
from urllib.parse import parse_qs


def esc(value):
    return html.escape(value or "")

query = os.environ.get("QUERY_STRING", "")
params = parse_qs(query)
name = params.get("name", ["anonymous"])[0]

print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("<head>")
print("<meta charset=\"utf-8\">")
print("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
print("<title>CGI GET demo · webserv</title>")
print("<link rel=\"stylesheet\" href=\"/css/style.css\">")
print("</head>")
print("<body>")
print("<header class=\"nav\"><div class=\"nav-inner\">")
print("<a href=\"/index.html\" class=\"brand\"><span class=\"brand-dot\"></span><span><span class=\"brand-prompt\">~/</span>webserv</span></a>")
print("<nav class=\"nav-links\"><a href=\"/cgi.html\">Back to CGI</a><a href=\"/index.html\">Home</a></nav>")
print("</div></header>")
print("<main class=\"fade-in\">")
print("<section class=\"container\">")
print("<span class=\"eyebrow\">// Python CGI GET</span>")
print("<h1>CGI GET is working</h1>")
print("<p class=\"lead\" style=\"color:var(--muted)\">Hello, <strong>%s</strong>. This page was generated by <code>test.py</code>.</p>" % esc(name))
print("</section>")
print("<section class=\"section container\"><div class=\"grid\">")
for key in ["REQUEST_METHOD", "QUERY_STRING", "SCRIPT_NAME", "PATH_INFO", "SERVER_PROTOCOL", "SERVER_PORT", "SERVER_NAME"]:
    print("<div class=\"card\"><h3>%s</h3><p><code>%s</code></p></div>" % (esc(key), esc(os.environ.get(key, ""))))
print("</div></section>")
print("</main>")
print("<footer><div class=\"container\"><span>webserv</span><span class=\"sep\">/</span><span>CGI demo</span></div></footer>")
print("</body></html>")
