server {
    listen 127.0.0.1:8080;
    server_name webserv_demo;

    root ./www-demo;
    index index.html;
    client_max_body_size 10485760;

    error_page 400 ./www-demo/errors/400.html;
    error_page 403 ./www-demo/errors/403.html;
    error_page 404 ./www-demo/errors/404.html;
    error_page 405 ./www-demo/errors/405.html;
    error_page 413 ./www-demo/errors/413.html;
    error_page 500 ./www-demo/errors/500.html;
    error_page 501 ./www-demo/errors/501.html;
    error_page 502 ./www-demo/errors/502.html;
    error_page 504 ./www-demo/errors/504.html;

    location / {
        methods GET;
        root ./www-demo;
        index index.html;
        autoindex off;
        upload_enable off;
        session_enable on;
        session_path /session;
    }

    location /files {
        methods GET;
        root ./www-demo/files;
        autoindex on;
        upload_enable off;
    }

    location /public {
        methods GET;
        root ./www-demo/public;
        autoindex on;
        upload_enable off;
    }

    location /upload {
        methods POST;
        root ./www-demo;
        autoindex off;
        upload_enable on;
        upload_store ./www-demo/uploads;
    }

    location /uploads {
        methods GET DELETE;
        root ./www-demo/uploads;
        autoindex on;
        upload_enable off;
    }

    location /cgi-bin {
        methods GET POST;
        root ./www-demo/cgi-bin;
        autoindex off;
        upload_enable off;
        cgi .py /usr/bin/python3;
    }

    location /redirect-me {
        methods GET;
        return 301 /index.html;
    }
}
