server {
    listen 127.0.0.1:8098;
    server_name timeout_test;

    root ./www;
    index index.html;
    client_max_body_size 1048576;
    client_timeout 5;

    error_page 404 ./www/errors/404.html;

    location / {
        methods GET;
        root ./www;
        index index.html;
        autoindex off;
        upload_enable off;
    }
}